added some actions, added seed data, changed the seed Dockerfile added table components

diff --git a/db/docker/mongodb_seed/Dockerfile b/db/docker/mongodb_seed/Dockerfile
--- a/db/docker/mongodb_seed/Dockerfile
+++ b/db/docker/mongodb_seed/Dockerfile
@@ -1,6 +1,32 @@
 ARG MONGO_VERSION
+ARG DATA_PATH=/data
 
 FROM mongo:${MONGO_VERSION}
 
-COPY init.json /init.json
-CMD mongoimport --host mongo --db einsatzplan --collection employees --type json --file /init.json --jsonArray
+# change shell in order to use arrays
+SHELL ["/bin/bash", "-c"]
+
+COPY . ${DATA_PATH}
+
+RUN echo "Starting data import..."
+
+# define the collections to import (name = fileName(.json) = collectionName(toUpper))
+CMD collections=("employee" "role" "group"); \
+    for name in "${collections[@]}"; do \
+      collection=$(echo $name | awk '{print toupper(substr($0,1,1))substr($0,2)}'); \
+      file="${DATA_PATH}/${name}.json"; \
+      if [ -f "$file" ]; then \
+        echo "Importing Collection '$collection'..."; \
+        if mongoimport --host mongo --db einsatzplan --collection $collection --type json --file $file --jsonArray; then \
+          echo "Successfully imported Collection '$collection'."; \
+        else \
+          echo "Failed to import Collection '$collection'."; \
+          exit 1; \
+        fi; \
+      else \
+        echo "File '$file' not found./nPlease provide a valid name which matches the file and which is also a json"; \
+        exit 1; \
+      fi; \
+    done
+
+RUN echo "Data import completed."
